name: CI

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:

  lint:
    name: "Lint"
    env:
      CI: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12.x

    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
         ${{ runner.os }}-yarn-
    - name: yarn install
      run: yarn
    - name: lint
      run: yarn lint:js

  floating:
    name: "Floating dependencies"
    env:
      CI: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        try-scenario: [
          ember-lts-3.12,
          ember-lts-3.16,
          ember-lts-3.20,
          # ember-beta,
          # ember-release,
        ]
    steps:
    - uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12.x

    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
         ${{ runner.os }}-yarn-
    - name: yarn install
      run: yarn
    - name: test
      run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
